package com.tushar.beans.webrowset;

import java.io.FileReader;
import java.sql.Connection;
import java.sql.DriverManager;

import javax.sql.rowset.RowSetFactory;
import javax.sql.rowset.RowSetProvider;
import javax.sql.rowset.WebRowSet;

public class WebRowSetProgram2 {
	public static void main(String[] args) {
		/*
		  In xml file which is generated by WebRowSetProgram1 program in that needs change during insertion in database
		  This type of data will be there during database to xml file which uses the currentRow tag.
			<data>
				<currentRow>
      				<columnValue>1</columnValue>
      				<columnValue>Tushar</columnValue>
      				<columnValue>IT</columnValue>
      				<columnValue>2500.00</columnValue>
    			</currentRow>
    		</data>
    		
    		This type of data will be there when we want insert data from xml file to database the change is only of
    		inserRow tag is used during insertion.
    		
		  	<data>
    			<insertRow>
      				<columnValue>8</columnValue>
      				<columnValue>Tushar</columnValue>
      				<columnValue>IT</columnValue>
      				<columnValue>2500.00</columnValue>
    			</insertRow>
    		</data>
		*/
		try(Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/JDBCDB", "root", "root")) {
			connection.setAutoCommit(false);
			
			RowSetFactory rowSetFactory = RowSetProvider.newFactory();
			WebRowSet webRowSet = rowSetFactory.createWebRowSet();
			webRowSet.setCommand("select * from employee");
			webRowSet.execute(connection);
			
			FileReader fileReader = new FileReader("/Users/tushar/JDBC/D_JDBC_Programs_2/src/com/tushar/beans/webrowset/employeeFileToDatabase.xml");
			webRowSet.readXml(fileReader);
			webRowSet.moveToCurrentRow();
			webRowSet.acceptChanges();
			System.out.println("Employee data inserted successfully.");
			fileReader.close();
			webRowSet.close();
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
	}
}
